# Generated by Django 2.1.5 on 2019-02-21 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_summer_note'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='image',
        ),
    ]
